baseURL = 'https://www.kliot-lab.xyz'
title = 'The Mite(y) Research Group'
theme = "ananke"
languageCode = 'en-uk'

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Kliot lab: researching mite-plant interactions"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = ""
  recent_posts_number = 2
  body_classes = "helvetica bg-near-white"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/adi-kliot/"
color = "#f4f4f4"

[[params.ananke_socials]]
name = "researchgate-square"
url = "https://www.researchgate.net/profile/Adi-Kliot"
color = "#f4f4f4"

[[params.ananke_socials]]
name = "google-scholar-square"
url = "https://scholar.google.co.uk/citations?user=ifC_aRIAAAAJ&hl=en&oi=ao"
color = "#f4f4f4"